server:
  port: 8080
  servlet:
    context-path: /sell


#logging:
#  pattern:
#    console: "%d ----- %mag%n "
#  file:
#    path: D:\MyCode\sell\   # 日志输出的路径和文件
#  level:
#    com.moon.sell.SellApplicationTests: debug   #  对特定类 设置日志打印级别


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.110/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null     # 让字段的空字段不返回


wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc